name: "Upload SARIF"

on:
  push:
    branches: [main]

jobs:
  Upload-SARIF:
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2