name: Upload SARIF
on: [push]
jobs:
  Upload-Sarif:
    runs-on: ubuntu-latest
    steps:
      - name: Uploading SARIF
        uses: github/codeql-action/upload-sarif@v2
        sarif-file: ../../results/report.sarif.json